name: TastyIgniter Core CI

on:
  push:
    branches: [ $default-branch, v4, release/*, feature/*, hotfix/* ]
  pull_request:
    branches: [ $default-branch, v4, release/*, feature/*, hotfix/* ]

jobs:
  build-assets:
    uses: tastyigniter/workflows/.github/workflows/build-assets.yml@main
  php-lint:
    needs: build-assets
    if: ${{ always() && needs.build-assets.result == 'success' }}
    uses: tastyigniter/workflows/.github/workflows/php-lint.yml@main
  php-tests:
    needs: php-lint
    if: ${{ always() && needs.php-lint.result == 'success' }}
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]
    uses: tastyigniter/workflows/.github/workflows/php-tests.yml@main
    with:
      php-version: ${{ matrix.target }}
